### ISSUE TITLE
[question] why having a copy of ~/.vim/autoload/plug.vim ? 

### ISSUE THREAD

**Issue by lmarvaud** [haomingw/dotfiles#2]
Is there a reason for adding a copy of the `~/.vim/autoload/plug.vim`, instead of using the command in [the file](https://github.com/haomingw/dotfiles/blob/63c23da9b7f4361cf25bc916e8abf0c5bddaad12/vim/vim/autoload/plug.vim#L6) :

```sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

**Comment by haomingw** [comment]
no particular reason, just to save a copy at local and not to depend on `curl` which is not installed by default on ubuntu
